// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BuydressTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void buydress() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".hovered .quick-view > span")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.id("color_15")).click();
    driver.findElement(By.id("group_1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("group_1"));
      dropdown.findElement(By.xpath("//option[. = 'M']")).click();
    }
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".cross")).click();
    driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .replace-2x")).click();
    driver.findElement(By.id("color_14")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.findElement(By.cssSelector(".cross")).click();
    driver.findElement(By.linkText("Quick view")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".icon-plus")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".cross")).click();
    driver.findElement(By.cssSelector(".hovered .quick-view > span")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".cross")).click();
    driver.findElement(By.cssSelector("b")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
    driver.findElement(By.cssSelector(".cheque-indent > .dark")).click();
  }
}
